config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  scope :monitoring do
    # Sidekiq Basic Auth from routes on production environment
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:SIDEKIQ_AUTH_USERNAME))) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:SIDEKIQ_AUTH_PASSWORD)))
    end if Rails.env.production?
    mount Sidekiq::Web, at: '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks' # Ensure this is correctly defined
  }

  root to: 'home#index'

  post Rails.application.credentials.dig(:google_forms_url) => 'webhooks#callback'

  resources :profiles, only: %i[show new update]
  resources :print_makers

  namespace :customers do
    resources :orders do
      member do
        delete :remove_model
        delete :remove_image
      end
    end
  end

  namespace :print_makers do
    resources :orders do
      collection do
        get :archived_orders
        get :available_orders
      end
    end

    resources :order_invitations do
      member do
        get 'reject'
        get 'accept'
      end
    end

    resources :print_maker_orders, only: %i[new create update] do
      member do
        patch :close_order
      end
    end
  end

  namespace :super_admins do
    resources :users, only: %i[index show update] do
      collection do
        post :update_roles
      end
    end
  end

  namespace :print_maker_admins do
    resources :orders, only: %i[index show] do
      member do
        post :approve_order
        post :reject_order
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many_attached :images, dependent: :purge
  has_many_attached :models, dependent: :purge
  has_many :print_maker_orders, dependent: :destroy
  has_many :print_makers, through: :print_maker_orders
  has_many :order_invitations, dependent: :destroy
  has_many :order_filaments, dependent: :destroy
  has_many :filaments, through: :order_filaments
  belongs_to :orderable, polymorphic: true

  # after_create :send_order_invitations

  scope :available_orders, -> { where(status: ['approved', 'in_progress']) } 

  enum status: { pending: 'pending', approved: 'approved', rejected: 'rejected', in_progress: 'in_progress', completed: 'completed', canceled: 'canceled' }

  def complition_percentage
    (total_completed_quantity.to_f / quantity.to_f * 100).round(2).to_i
  end

  def reserved_percentage
    (total_reserved_quantity.to_f / quantity.to_f * 100).round(2).to_i
  end

  def total_completed_quantity
    print_maker_orders.sum(:completed_quantity)
  end

  def total_reserved_quantity
    print_maker_orders.sum(:reserved_quantity)
  end

  def status_value
    self.class.statuses.key(self.status)
  end

  def available_quantity
    quantity - total_completed_quantity
  end

  private

  # def send_order_invitations
  #   SendInvitation.perform_async(id)
  # end
end

app/models/print_maker.rb
class PrintMaker < ApplicationRecord
  belongs_to :worker

  has_many :print_makers_filaments, dependent: :destroy
  has_many :filaments, through: :print_makers_filaments
  has_many :order_invitations, dependent: :destroy
  has_many :print_maker_orders, dependent: :destroy
  has_many :orders, through: :order_invitations

  enum status: { ready: 'Готовий', busy: 'Зайнятий', cant_take_orders: 'Не можу працювати' }
  enum rank: { newbie: 'newbie', pro: 'pro', expert: 'expert', guru: 'guru' }

  def available_orders
    orders.joins(:order_invitations)
          .where(order_invitations: { status: ['pending', 'accepted'] }).distinct
  end

  def account_type
    'print_maker'
  end
end

app/controllers/customers/orders_controller.rb
module Customers
  class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_customer!

    def index
      @orders = current_user.customer&.orders || current_user.print_maker_admin&.orders || current_user.super_admin&.orders
    end

    def show
      @order = Order.find(params[:id])
    end

    def new
      @order = Order.new
    end

    def create
      @order = Order.new(order_params)
      @order.orderable = current_user.customer || current_user.print_maker_admin || current_user.super_admin

      if @order.save
        redirect_to customers_orders_path, notice: 'Замовлення створено'
      end
    end

    def edit
      @order = Order.find(params[:id])
    end

    def update
      @order = Order.find(params[:id])

      params[:order][:images].select(&:present?).each do |image|
        @order.images.attach(image)
      end

      params[:order][:models].select(&:present?).each do |model|
        @order.models.attach(model)
      end

      if @order.update(order_params.except(:models, :images))
        redirect_to customers_orders_path, notice: 'Замовлення оновлено'
      end
    end

    def remove_image
      image = ActiveStorage::Attachment.find(params[:image_id])
      image.purge
      redirect_back(fallback_location: root_path, notice: 'Зображення видалено.')
    end

    def remove_model
      @order = Order.find(params[:id])
      model = @order.models.find(params[:model_id])
      model.purge
      redirect_to edit_customers_order_path(@order), notice: 'Модель було успішно видалено.'
    end

    private

    def ensure_customer!
      return if current_user.customer || current_user.print_maker_admin || current_user.super_admin

      redirect_to root_path, alert: "Access denied!"
    end

    def order_params
      clear_empty_values

      params.require(:order).permit(
        :name,
        :description,
        :quantity,
        :deadline,
        :customer_id,
        filament_ids: [],
        images: [],
        models: []
      )
    end

    def clear_empty_values
      params['order']['filament_ids'].reject!(&:blank?)
    end
  end
end

app/controllers/print_maker_admins/orders_controller.rb
module PrintMakerAdmins
  class OrdersController < ApplicationController
    before_action :find_data, only: %i[reject_order approve_order show]

    def index
      @orders = Order.all
    end

    def show
      @order
    end

    def reject_order
      return unless @order.rejected!

      redirect_to print_maker_admins_orders_path, notice: 'Ви вiдхилили замовлення'
    end

    def approve_order
      return unless @order.approved!

      redirect_to print_maker_admins_orders_path, notice: 'Ви прийняли замовлення'
    end

    private

    def find_data
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/print_makers/order_invitations_controller.rb
module PrintMakers
  class OrderInvitationsController < ApplicationController
    before_action :find_data

    def accept
      @order_inivitation.accept!
      redirect_to print_makers_order_path(@order), notice: 'Ви прийняли запрошення'
    end

    def reject
      @order_inivitation.reject!
      redirect_to available_orders_print_makers_orders_path, alert: 'Ви відхилили запрошення'
    end

    private

    def find_data
      @order_inivitation = OrderInvitation.find_by(print_maker_id: current_user.id, order_id: params[:id])
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/print_makers/orders_controller.rb
module PrintMakers
  class OrdersController < ApplicationController
    def index
      @orders = current_user.print_maker.orders
    end

    def show
      @order = Order.find(params[:id])
      @print_maker_order = PrintMakerOrder.not_finished.find_or_create_by(print_maker_id: current_user.print_maker.id, order_id: @order.id)
      @available_quantity = @order.available_quantity
    end

    def available_orders
      @available_orders = Order.available_orders
    end

    def archived_orders
      @archived_orders = PrintMakerOrder.completed.where(print_maker_id: current_user.print_maker.id)
    end
  end
end

app/controllers/print_makers/print_maker_orders_controller.rb
module PrintMakers
  class PrintMakerOrdersController < ApplicationController
    before_action :find_data

    def update
      if @print_maker_order.update(print_maker_order_params)
        @print_maker_order.in_progress!
        redirect_to print_makers_order_path(@order), notice: 'Замовлення було успішно оновлено.'
      end
    end

    def close_order
      @print_maker_order.completed!
      redirect_to available_orders_print_makers_orders_path, notice: "Замовлення успішно закрито."
    end

    private

    def find_data
      @order = Order.find(params[:id])
      @print_maker_order = PrintMakerOrder.not_finished.find_or_initialize_by(print_maker_id: current_user.print_maker.id, order_id: @order.id)
    end

    def print_maker_order_params
      params.require(:print_maker_order).permit(
        :reserved_quantity,
        :completed_quantity,
        print_maker: current_user.print_maker
        )
    end
  end
end

app/controllers/print_makers_controller.rb
class PrintMakersController < ApplicationController
  def show
    @print_maker = current_user.print_maker
  end

  def edit
    @print_maker = current_user.print_maker
  end

  def update
    @print_maker = current_user.print_maker
    if @print_maker.update(print_maker_params)
      redirect_to profile_path, notice: 'Статус успішно оновлено.'
    else
      render :show, alert: 'Не вдалося оновити статус.'
    end
  end

  private

  def print_maker_params
    params.require(:print_maker).permit(
      :status,
      :name,
      filament_ids: []
    )
  end
end

app/helpers/print_maker_helper.rb
module PrintMakerHelper
end

app/views/print_makers/orders/_archived_order.html.erb
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-header"><%= archived_order.order.name %></div>
    <div class="card-body">
      <p class="card-text"><%= archived_order.order.description %></p>
      <div class='complition-content'>
        <p class="card-text mt-2"><b>Взято до роботи:</b> <%= archived_order.reserved_quantity %></p>
        <p class="card-text mt-2"><b>Вироблено:</b> <%= archived_order.completed_quantity %></p>
        <p class="card-text mt-2"><b>ТТН:</b> <%= archived_order.track_number %></p>
  </div>
</div>

app/views/print_makers/orders/_available_order.html.erb
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-header"><%= order.name %></div>
    <div class="card-body">
      <p class="card-text"><%= order.description %></p>
      <p class="card-text"><%= order.filaments.pluck(:name).map(&:capitalize).join(", ") %></p>
      <div class='complition-content'>
        <p class="card-text mt-2">Вироблено </p>
        <div class="progress mb-2">
          <div class="progress-bar bg-success" role="progressbar" style="width: <%= order.complition_percentage%>%;" aria-valuenow="<%= order.complition_percentage%>" aria-valuemin="0" aria-valuemax="100"><%= order.complition_percentage%>%</div>
        </div>
        <p class="card-text"><b><%= order.total_completed_quantity %> </b>з <%= order.quantity %></p>
        <p class="card-text mt-2">Взято до роботи </p>
        <div class="progress mb-2">
          <div class="progress-bar" role="progressbar" style="width: <%= order.reserved_percentage%>%;" aria-valuenow="<%= order.reserved_percentage%>" aria-valuemin="0" aria-valuemax="100"><%= order.reserved_percentage%>%</div>
        </div>
        <p class="card-text"><b><%= order.total_reserved_quantity %> </b>з <%= order.quantity %></p>
    </div>
      <a href="<%= print_makers_order_path(order) %>" class=" mt-2 btn btn-primary">Переглянути замовлення</a>
    </div>
  </div>
</div>

app/views/print_makers/orders/archived_orders.html.erb
<h1>Завершені замовлення</h1>

<% if @archived_orders.empty? %>
  <p>Немає завершених замовленьь</p>
<% else %>
  <div class="container">
    <div class="row">
      <% @archived_orders.each do |archived_order| %>
        <%= render 'archived_order', archived_order: archived_order %>
      <% end %>
    </div>
<% end %>

app/views/print_makers/orders/available_orders.html.erb
<h1>Доступні замовлення</h1>

<% if @available_orders.empty? %>
  <p>Немає доступних замовлень</p>
<% else %>
  <div class="container">
    <div class="row">
      <% @available_orders.each do |order| %>
        <%= render 'available_order', order: order %>
      <% end %>
    </div>
<% end %>

app/views/print_makers/orders/index.html.erb
<h1>Замовлення</h1>

<% @current_user.customer.orders.each do |order| %>
  <%= order.name %>
<% end %>

app/views/print_makers/orders/show.html.erb
<div class="row">
  <div class="d-flex align-items-center mt-4">
    <p class="fw-bold mb-0">Назва:</p>
    <p class="fw-normal mb-0 ms-2"><%= @order.name %></p>
  </div>
  <div class="d-flex align-items-center mt-4">
    <p class="fw-bold mb-0">Опис:</p>
    <p class="fw-normal mb-0 ms-2"><%= @order.description %></p>
  </div>

  <div class="d-flex align-items-center mt-4">
    <p class="fw-bold mb-0">Матерiал:</p>
    <p class='fw-normal mb-0 ms-2'><%= @order.filaments.pluck(:name).map(&:capitalize).join(", ") %></p>
  </div>

  
      <div class='complition-content'>
        <hr class="w-50">
          <p class="card-text">Доступно до роботи: <b><%= @available_quantity %></b></p>
        <% if @print_maker_order.reserved_quantity.present? %>
          <p class="card-text">Взято до роботи: <b><%= @print_maker_order.reserved_quantity %></b></p>
        <% end %>

        <% if @print_maker_order.completed_quantity.present? %>
          <p class="card-text">Виконано: <b><%= @print_maker_order.completed_quantity %> </b>з <%= @print_maker_order.reserved_quantity %></p>
        <% end %>
        <hr class="w-50">
      </div>
      </div>
    </div>
  </div>


  <% if @order.images.attached? %>
    <p class='fw-bold mb-0'>Зображення замовлення:</p>
    <% @order.images.each do |image| %>
      <%= link_to rails_blob_path(image, disposition: "inline"), target: "_blank", rel: "noopener noreferrer" do %>
        <%= image_tag(image.variant(resize_to_fill: [200, nil])) %>
      <% end %>
    <% end %>
    <hr class="w-50">
  <% end %>

<% if PrintMakers::OrderPolicy.new(current_user.print_maker, @order).can_see_attached_model? %>
  <% if @order.models.attached? %>
    <div>
      <p class='fw-bold mb-0'>Моделі:</p>
        <% @order.models.each do |model| %>
          <p class="card-text mt-1"><%= link_to File.basename(model.filename.to_s), rails_blob_path(model, disposition: 'attachment') %></p>
        <% end %>
    </div>
  <% end %>
<% end %>

    <hr class="w-50">
    <%= simple_form_for @print_maker_order, url: print_makers_print_maker_order_path(@order), method: :patch do |f| %>
      <% if @print_maker_order.reserved_quantity.nil? %>
        <%= f.input :reserved_quantity, label: 'Я планую зробити',  wrapper_html: { class: 'w-50' }, input_html: { min: 1 }, required: true %>
        <%= f.button :submit, 'Оновити', class: 'btn btn-primary' %>
      <% end %>
      <% if @print_maker_order.reserved_quantity && @print_maker_order.reserved_quantity != @print_maker_order.completed_quantity %>
        <%= f.input :completed_quantity, label: 'Я зробив',  wrapper_html: { class: 'w-50' }, input_html: { min: 1 }, required: true %>
        <%= f.input :track_number, label: 'ТТН:',  wrapper_html: { class: 'w-50' }, required: false %>
        <%= f.button :submit, 'Оновити', class: 'btn btn-primary' %>
      <% end %>

    <% end %>

  <% if @print_maker_order.reserved_quantity %>
    <hr class="w-50"> 
    <%= button_to 'Завершити замовлення', close_order_print_makers_print_maker_order_path(@order, print_maker_order: @print_maker_order), method: :patch, class: 'btn btn-primary' %>
  <% end %>
</div>