config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  scope :monitoring do
    # Sidekiq Basic Auth from routes on production environment
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:SIDEKIQ_AUTH_USERNAME))) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:SIDEKIQ_AUTH_PASSWORD)))
    end if Rails.env.production?
    mount Sidekiq::Web, at: '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks' # Ensure this is correctly defined
  }

  root to: 'home#index'

  post Rails.application.credentials.dig(:google_forms_url) => 'webhooks#callback'

  resources :profiles, only: %i[show new update]
  resources :print_makers

  namespace :customers do
    resources :orders do
      member do
        delete :remove_model
        delete :remove_image
      end
    end
  end

  namespace :print_makers do
    resources :orders do
      collection do
        get :archived_orders
        get :available_orders
      end
    end

    resources :order_invitations do
      member do
        get 'reject'
        get 'accept'
      end
    end

    resources :print_maker_orders, only: %i[new create update] do
      member do
        patch :close_order
      end
    end
  end

  namespace :super_admins do
    resources :users, only: %i[index show update] do
      collection do
        post :update_roles
      end
    end
  end

  namespace :print_maker_admins do
    resources :orders, only: %i[index show] do
      member do
        post :approve_order
        post :reject_order
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :worker
  has_many :orders, as: :orderable, dependent: :destroy

  def account_type
    'customer'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many_attached :images, dependent: :purge
  has_many_attached :models, dependent: :purge
  has_many :print_maker_orders, dependent: :destroy
  has_many :print_makers, through: :print_maker_orders
  has_many :order_invitations, dependent: :destroy
  has_many :order_filaments, dependent: :destroy
  has_many :filaments, through: :order_filaments
  belongs_to :orderable, polymorphic: true

  # after_create :send_order_invitations

  scope :available_orders, -> { where(status: ['approved', 'in_progress']) } 

  enum status: { pending: 'pending', approved: 'approved', rejected: 'rejected', in_progress: 'in_progress', completed: 'completed', canceled: 'canceled' }

  def complition_percentage
    (total_completed_quantity.to_f / quantity.to_f * 100).round(2).to_i
  end

  def reserved_percentage
    (total_reserved_quantity.to_f / quantity.to_f * 100).round(2).to_i
  end

  def total_completed_quantity
    print_maker_orders.sum(:completed_quantity)
  end

  def total_reserved_quantity
    print_maker_orders.sum(:reserved_quantity)
  end

  def status_value
    self.class.statuses.key(self.status)
  end

  def available_quantity
    quantity - total_completed_quantity
  end

  private

  # def send_order_invitations
  #   SendInvitation.perform_async(id)
  # end
end

app/controllers/customers/orders_controller.rb
module Customers
  class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_customer!

    def index
      @orders = current_user.customer&.orders || current_user.print_maker_admin&.orders || current_user.super_admin&.orders
    end

    def show
      @order = Order.find(params[:id])
    end

    def new
      @order = Order.new
    end

    def create
      @order = Order.new(order_params)
      @order.orderable = current_user.customer || current_user.print_maker_admin || current_user.super_admin

      if @order.save
        redirect_to customers_orders_path, notice: 'Замовлення створено'
      end
    end

    def edit
      @order = Order.find(params[:id])
    end

    def update
      @order = Order.find(params[:id])

      params[:order][:images].select(&:present?).each do |image|
        @order.images.attach(image)
      end

      params[:order][:models].select(&:present?).each do |model|
        @order.models.attach(model)
      end

      if @order.update(order_params.except(:models, :images))
        redirect_to customers_orders_path, notice: 'Замовлення оновлено'
      end
    end

    def remove_image
      image = ActiveStorage::Attachment.find(params[:image_id])
      image.purge
      redirect_back(fallback_location: root_path, notice: 'Зображення видалено.')
    end

    def remove_model
      @order = Order.find(params[:id])
      model = @order.models.find(params[:model_id])
      model.purge
      redirect_to edit_customers_order_path(@order), notice: 'Модель було успішно видалено.'
    end

    private

    def ensure_customer!
      return if current_user.customer || current_user.print_maker_admin || current_user.super_admin

      redirect_to root_path, alert: "Access denied!"
    end

    def order_params
      clear_empty_values

      params.require(:order).permit(
        :name,
        :description,
        :quantity,
        :deadline,
        :customer_id,
        filament_ids: [],
        images: [],
        models: []
      )
    end

    def clear_empty_values
      params['order']['filament_ids'].reject!(&:blank?)
    end
  end
end

app/controllers/print_maker_admins/orders_controller.rb
module PrintMakerAdmins
  class OrdersController < ApplicationController
    before_action :find_data, only: %i[reject_order approve_order show]

    def index
      @orders = Order.all
    end

    def show
      @order
    end

    def reject_order
      return unless @order.rejected!

      redirect_to print_maker_admins_orders_path, notice: 'Ви вiдхилили замовлення'
    end

    def approve_order
      return unless @order.approved!

      redirect_to print_maker_admins_orders_path, notice: 'Ви прийняли замовлення'
    end

    private

    def find_data
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/print_makers/orders_controller.rb
module PrintMakers
  class OrdersController < ApplicationController
    def index
      @orders = current_user.print_maker.orders
    end

    def show
      @order = Order.find(params[:id])
      @print_maker_order = PrintMakerOrder.not_finished.find_or_create_by(print_maker_id: current_user.print_maker.id, order_id: @order.id)
      @available_quantity = @order.available_quantity
    end

    def available_orders
      @available_orders = Order.available_orders
    end

    def archived_orders
      @archived_orders = PrintMakerOrder.completed.where(print_maker_id: current_user.print_maker.id)
    end
  end
end

app/views/customers/orders/_order.html.erb
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-header"><%= order.name %></div>
    <div class="card-body">
      <p class="card-text"><%= order.description %></p>
      <p class='card-text'><%= order.filaments.pluck(:name).map(&:capitalize).join(", ") %></p>
      <p class="card-text">Статус: <%= I18n.t("enums.order.status.#{order.status}") %></p>
      <div class='complition-content'>
        <p class="card-text mt-2">Вироблено </p>
        <div class="progress mb-2">
          <div class="progress-bar bg-success" role="progressbar" style="width: <%= order.complition_percentage%>%;" aria-valuenow="<%= order.complition_percentage%>" aria-valuemin="0" aria-valuemax="100"><%= order.complition_percentage%>%</div>
        </div>
        <p class="card-text"><b><%= order.complition_percentage %> </b>з <%= order.quantity %></p>
        <p class="card-text mt-2">Взято до роботи </p>
        <div class="progress mb-2">
          <div class="progress-bar" role="progressbar" style="width: <%= order.reserved_percentage%>%;" aria-valuenow="<%= order.reserved_percentage%>" aria-valuemin="0" aria-valuemax="100"><%= order.reserved_percentage%>%</div>
        </div>
        <p class="card-text"><b><%= order.reserved_percentage %> </b>з <%= order.quantity %></p>
    </div>
      <a href="<%= customers_order_path(order) %>" class=" mt-2 btn btn-primary">Переглянути замовлення</a>
    </div>
  </div>
</div>

app/views/customers/orders/edit.html.erb
<%= simple_form_for @order, url: customers_order_path, html: { class: 'needs-validation', novalidate: true, multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Назва', required: true, input_html: { class: 'form-control' } %>
    <%= f.input :description, label: 'Опис', as: :text, required: true, input_html: { class: 'form-control', rows: 3 } %>
    <%= f.input :quantity, label: 'Кількість', as: :integer, required: true, input_html: { class: 'form-control', in: 1..1000, step: 1 } %>
    <%= f.label :filaments, 'Філамент:', class: 'form-label' %>
    <%= f.collection_check_boxes :filament_ids, Filament.all, :id, :name do |b| %>
      <%= b.label(class: "checkbox ml-1") { b.check_box + b.text.upcase } %>
    <% end %>

    <% if @order.images.attached? %>
      <h3>Зображення:</h3>
      <div class="row">
        <% @order.images.each do |image| %>
          <div class="col-md-2">
            <div class="card">
              <%= image_tag image, class: 'card-img-top' %>
              <div class="card-body">
                <%= link_to 'Видалити', remove_image_customers_order_path(image_id: image.id), data: { "turbo-method": :delete }, class: 'btn btn-danger' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <hr>
    <% end %>

    <%= f.input :images, as: :file, required: false, class: 'mt-4', input_html: { multiple: true, accept: 'image/jpeg,image/png'}, label: 'Завантажити зображення' %>
    <hr>


    <% if @order.models.attached? %>
      <h3>Моделі:</h3>
      <div class="row">
        <% @order.models.each do |model| %>
          <div class="col-md-2">
            <div class="card">
              <%= link_to model.filename.to_s, rails_blob_path(model, disposition: "attachment") %>
              <div class="card-body">
              <%= link_to remove_model_customers_order_path(model_id: model.id), data: { "turbo-method": :delete }, class: "btn btn-danger" do %>
                Видалити
              <% end %>
              </div>
            </div>
        <% end %>
      </div>
      <hr>
    <% end %>

      <%= f.input :models, as: :file, input_html: { multiple: true, name: 'order[models][]', accept: '.zip,.stl', required: true }, label: 'Завантажити модель' %>
  </div>

  <div class="form-actions mt-5">
    <%= f.button :submit, "Зберегти", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/customers/orders/index.html.erb
<h1>Мої замовлення</h1>

<% if @orders.empty? %>
  <p>У вас немає замовлень</p>
<% else %>
  <div class="container">
    <div class="row">
        <%= render @orders %>
    </div>
<% end %>

app/views/customers/orders/new.html.erb
<h1>Створення замовлення</h1>

<%= simple_form_for :order, url: customers_orders_path, local: true, html: { multipart: true } do |f| %>
  <%= f.input :name, label: 'Назва', input_html: { class: "form-control", required: true } %>
  <%= f.input :description, label: 'Опис', input_html: { class: "form-control", required: true } %>
  <%= f.input :quantity, label: 'Кількість', as: :integer, input_html: { min: 1, max: 10000, step: 1, class: "form-control", required: true } %>
  <%= f.label :filaments, 'Філамент:', class: 'form-label' %>
   <%= f.collection_check_boxes :filament_ids, Filament.all, :id, :name do |b| %>
      <%= b.label(class: "checkbox ml-1") { b.check_box + b.text.upcase } %>
    <% end %>
  <%= f.input :deadline, as: :date, html5: true, label: 'Виконати до', input_html: { class: "form-control w-50", required: true } %>
  <%= f.input :images, as: :file, required: false, input_html: { multiple: true, name: 'order[images][]', accept: 'image/jpeg,image/png'}, label: 'Завантажити зображення' %>
  <%= f.input :models, as: :file, input_html: { multiple: true, name: 'order[models][]', accept: '.zip,.stl', required: true }, label: 'Завантажити модель' %>

  <%= f.button :submit, 'Створити замовлення', class: 'btn btn-primary' %>
<% end %>

app/views/customers/orders/show.html.erb
<div class="row">
  <div class="d-flex align-items-center mt-4">
    <p class="fw-bold mb-0">Назва:</p>
    <p class="fw-normal mb-0 ms-2"><%= @order.name %></p>
  </div>
  <div class="d-flex align-items-center mt-4">
    <p class="fw-bold mb-0">Опис:</p>
    <p class="fw-normal mb-0 ms-2"><%= @order.description %></p>
  </div>


        <div class='complition-content'>
        <hr class="w-50">
          <p class="card-text">Вироблено: <b><%= @order.total_completed_quantity %> </b>з <%= @order.quantity %></p>
          <p class="card-text">Взято до роботи: <b><%= @order.total_reserved_quantity %> </b>з <%= @order.quantity %></p>
        <hr class="w-50">
      </div>
      </div>
    </div>
  </div>


  <% if @order.images.attached? %>
    <p class='fw-bold mb-0'>Зображення:</p>
    <% @order.images.each do |image| %>
      <%= link_to rails_blob_path(image, disposition: "inline"), target: "_blank", rel: "noopener noreferrer" do %>
        <%= image_tag(image.variant(resize_to_fill: [200, nil])) %>
      <% end %>
    <% end %>
    <hr class="w-50">
  <% end %>

  <% if @order.models.attached? %>
    <div>
      <p class='fw-bold mb-0'>Моделі:</p>
        <% @order.models.each do |model| %>
          <p class="card-text mt-1"><%= link_to File.basename(model.filename.to_s), rails_blob_path(model, disposition: 'attachment') %></p>
        <% end %>
    </div>
  <% end %>

  <div class="edit-close-section mt-4">
    <%= link_to 'Редагувати замовлення', edit_customers_order_path(@order), class: 'btn btn-primary me-2' %>
  </div>
</div>