config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  scope :monitoring do
    # Sidekiq Basic Auth from routes on production environment
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:SIDEKIQ_AUTH_USERNAME))) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:SIDEKIQ_AUTH_PASSWORD)))
    end if Rails.env.production?
    mount Sidekiq::Web, at: '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks' # Ensure this is correctly defined
  }

  root to: 'home#index'

  post Rails.application.credentials.dig(:google_forms_url) => 'webhooks#callback'

  resources :profiles, only: %i[show new update]
  resources :print_makers

  namespace :customers do
    resources :orders do
      member do
        delete :remove_model
        delete :remove_image
      end
    end
  end

  namespace :print_makers do
    resources :orders do
      collection do
        get :archived_orders
        get :available_orders
      end
    end

    resources :order_invitations do
      member do
        get 'reject'
        get 'accept'
      end
    end

    resources :print_maker_orders, only: %i[new create update] do
      member do
        patch :close_order
      end
    end
  end

  namespace :super_admins do
    resources :users, only: %i[index show update] do
      collection do
        post :update_roles
      end
    end
  end

  namespace :print_maker_admins do
    resources :orders, only: %i[index show] do
      member do
        post :approve_order
        post :reject_order
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :worker
  has_many :orders, as: :orderable, dependent: :destroy

  def account_type
    'customer'
  end
end

app/models/filament.rb
class Filament < ApplicationRecord
  has_many :profiles_filaments
  has_many :profiles, through: :profiles_filaments
  has_many :order_filaments, dependent: :destroy
  has_many :orders, through: :order_filaments
  has_many :print_makers_filaments, dependent: :destroy

  enum name: { pla: 'PLA', abs: 'ABS', petg: 'PETG', tpu: 'TPU'}
end

app/models/order.rb
class Order < ApplicationRecord
  has_many_attached :images, dependent: :purge
  has_many_attached :models, dependent: :purge
  has_many :print_maker_orders, dependent: :destroy
  has_many :print_makers, through: :print_maker_orders
  has_many :order_invitations, dependent: :destroy
  has_many :order_filaments, dependent: :destroy
  has_many :filaments, through: :order_filaments
  belongs_to :orderable, polymorphic: true

  # after_create :send_order_invitations

  scope :available_orders, -> { where(status: ['approved', 'in_progress']) } 

  enum status: { pending: 'pending', approved: 'approved', rejected: 'rejected', in_progress: 'in_progress', completed: 'completed', canceled: 'canceled' }

  def complition_percentage
    (total_completed_quantity.to_f / quantity.to_f * 100).round(2).to_i
  end

  def reserved_percentage
    (total_reserved_quantity.to_f / quantity.to_f * 100).round(2).to_i
  end

  def total_completed_quantity
    print_maker_orders.sum(:completed_quantity)
  end

  def total_reserved_quantity
    print_maker_orders.sum(:reserved_quantity)
  end

  def status_value
    self.class.statuses.key(self.status)
  end

  def available_quantity
    quantity - total_completed_quantity
  end

  private

  # def send_order_invitations
  #   SendInvitation.perform_async(id)
  # end
end

app/models/order_filament.rb
class OrderFilament < ApplicationRecord
  belongs_to :order
  belongs_to :filament
end

app/models/order_invitation.rb
class OrderInvitation < ApplicationRecord
  belongs_to :order
  belongs_to :print_maker

  enum status: { pending: 'pending', accepted: 'accepted', rejected: 'rejected' }

  before_create :set_initial_status
  after_create :send_invitation_notification

  def accept!
    update(status: 'accepted')
  end

  def reject!
    update(status: 'rejected')
  end

  private

  def set_initial_status
    self.status ||= 'pending'
  end

  def send_invitation_notification
    SendInvitationNotification.perform_async(id)
  end
end

app/models/print_maker.rb
class PrintMaker < ApplicationRecord
  belongs_to :worker

  has_many :print_makers_filaments, dependent: :destroy
  has_many :filaments, through: :print_makers_filaments
  has_many :order_invitations, dependent: :destroy
  has_many :print_maker_orders, dependent: :destroy
  has_many :orders, through: :order_invitations

  enum status: { ready: 'Готовий', busy: 'Зайнятий', cant_take_orders: 'Не можу працювати' }
  enum rank: { newbie: 'newbie', pro: 'pro', expert: 'expert', guru: 'guru' }

  def available_orders
    orders.joins(:order_invitations)
          .where(order_invitations: { status: ['pending', 'accepted'] }).distinct
  end

  def account_type
    'print_maker'
  end
end

app/models/print_maker_admin.rb
class PrintMakerAdmin < ApplicationRecord
  belongs_to :worker
  has_many :orders, as: :orderable

  def account_type
    'print_maker_admin'
  end
end

app/models/print_maker_order.rb
class PrintMakerOrder < ApplicationRecord
  belongs_to :print_maker
  belongs_to :order

  enum status: { pending: 'pending', in_progress: 'in_progress', completed: 'completed' }

  scope :not_finished, -> { where.not(status: 'completed') }
  scope :completed, -> { where(status: 'completed') }

  def available_completed_quantity
    reserved_quantity
  end
end

app/models/print_makers_filament.rb
class PrintMakersFilament < ApplicationRecord
  belongs_to :print_maker
  belongs_to :filament
end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  belongs_to :worker
  has_many :orders, as: :orderable

  def account_type
    'super_admin'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_one :worker, dependent: :destroy
  has_one :customer, through: :worker
  has_one :print_maker, through: :worker
  has_one :print_maker_admin, through: :worker
  has_one :super_admin, through: :worker

  after_create :create_worker_for_user

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.avatar_url = auth.info.image
    end
  end

  private

  def create_worker_for_user
    create_worker(name: name) unless worker
  end
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
  belongs_to :user
  belongs_to :order
  has_many_attached :images, dependent: :purge
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :user
  has_one :print_maker, inverse_of: :worker
  has_one :customer, inverse_of: :worker
  has_one :print_maker_admin, inverse_of: :worker
  has_one :super_admin, inverse_of: :worker

  after_create :create_print_maker, if: -> { !user.print_maker.present? }

  def roles
    [].tap do |roles|
      roles.push(print_maker) if print_maker.present?
      roles.push(customer) if customer.present?
      roles.push(print_maker_admin) if print_maker_admin.present?
      roles.push(super_admin) if super_admin.present?
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to profile_path(current_user)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @current_user = current_user
    @print_maker = current_user.worker.print_maker
  end

  def edit
    @profile = current_user.profile
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'alert alert-success'
    when :alert then 'alert alert-danger'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/print_maker_helper.rb
module PrintMakerHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrintCrm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module", async: true %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <% if user_signed_in? %>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="#" class="nav-item nav-link active">Новини</a>
                    <% if current_user.print_maker %>
                      <%= link_to available_orders_print_makers_orders_path, class: 'nav-item nav-link',  data: { turbo: "false" }, method: :get do%>
                        Доступні замовлення
                      <% end %>
                      <%= link_to archived_orders_print_makers_orders_path, class: 'nav-item nav-link',  data: { turbo: "false" }, method: :get do%>
                        Завершені замовлення
                      <% end %>
                      <%= link_to profile_path(current_user), class: "nav-item nav-link", data: { turbo: "false" }, method: :get do %> 
                        <i class="bi bi-person-fill"></i>
                      <% end %>
                    <% end %>

                    <% if current_user.print_maker_admin || current_user.super_admin %>
                      <%= link_to print_maker_admins_orders_path, class: 'nav-item nav-link',  data: { turbo: "false" }, method: :get do%>
                        Перелiк замовлень
                      <% end %>
                    <% end %>
                    <% if current_user.customer || current_user.print_maker_admin || current_user.super_admin %>
                      <%= link_to new_customers_order_path, class: "nav-item nav-link", data: { turbo: "false" }, method: :get do %>
                        Створити замовлення
                      <% end %>

                      <%= link_to customers_orders_path, class: 'nav-item nav-link', data: { turbo: "false" }, method: :get do %>
                        Мої замовлення
                      <% end %>
                    <% end %>
                    <% if current_user.super_admin %>
                      <%= link_to super_admins_users_path, class: "nav-item nav-link", data: { turbo: "false" }, method: :get do %> 
                        Керування користувачами
                     <% end %>
                    <% end %>
                  <%# <a href="#" class="nav-item nav-link">
                    <i class="bi bi-bell-fill"></i>
                    <%# <span class="badge rounded-pill badge-notification bg-danger">1</span> %>
                  <%# </a> %>
                </div>
            </div>
          <% end %>

        </div>
    </nav>
  </head>

  <body>
    <div class="container">
    <%= render "shared/flash" %>
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |flash_type, message| %>
    <div class="<%= flash_class (flash_type.to_sym) %> alert-dismissible fade show" role="alert">
      <% unless message == true %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= message %>
      <% end %>
    </div>
  <% end %> 
</div>